### ISSUE TITLE
asking for root@0.tcp.ngrok.io's password

### ISSUE THREAD

**Issue by alex-mathew** [vdivakar/Colab-SSH-and-GDrive#1]

**Comment by vdivakar** [comment]
Hi, You need to enter ngrok's authorization token in your colab notebook. Copy this template and try running again.
https://github.com/vdivakar/Colab-SSH-and-GDrive/blob/master/ssh_colab.ipynb

**Comment by alex-mathew** [comment]
Thanks for the reply. I was running the same notebook. Copy pasted the wrong ssh key. Now it's working.

**Comment by ashok-arjun** [comment]
Hi @vdivakar I pasted the right authtoken, but `ssh` still asks for a password
