### ISSUE TITLE
Sorry but i got this error . Can you help me ?

### ISSUE THREAD

**Issue by huynth1801** [vdivakar/Colab-SSH-and-GDrive#4]
I run with your template notebook after running and i type command ssh in terminal i got this error ssh : connect to host 0.tcp.ngrok.io port 17xx9: Connection refused

Can you help me. Thank you

**Comment by vdivakar** [comment]
Hi, login to your ngrok account and check if the port/connection is still running. Otherwise restarting the ngrok port should help.
